sudo: false
language: php

php:
  - 7.2

addons:
  apt:
    packages:
      - parallel

install:
  - >
    composer install;

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running unit tests";
    .build/bin/phpunit -c Build/UnitTests.xml --coverage-clover .build/clover.xml
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    .build/bin/phpunit -c Build/FunctionalTests.xml
