sudo: false
language: php

php:
  - 7.2
  - 7.3

services:
  - mysql
  - postgresql


addons:
  apt:
    packages:
      - parallel

env:
  global:
    - CODACY_PROJECT_TOKEN=727c375148344e04973a6ee108d3967e
  matrix:
    - typo3DatabaseDriver=mysqli typo3DatabaseUsername=root typo3DatabaseHost=localhost typo3DatabaseName=test
    - typo3DatabaseDriver=pdo_pgsql typo3DatabaseUsername=postgres typo3DatabaseHost=localhost typo3DatabaseName=test
    - typo3DatabaseDriver=pdo_sqlite

cache:
  directories:
  - $HOME/.composer/cache

install:
  - >
    composer install --prefer-dist;
    composer build:package:link

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running unit tests";
    .build/bin/phpunit -c Build/UnitTests.xml
  - >
    echo;
    echo "Running functional tests";
    .build/bin/phpunit -c Build/FunctionalTests.xml --coverage-clover .build/coverage.xml

after_script:
  - >
    .build/bin/codacycoverage clover .build/coverage.xml
