sudo: false
language: php

php:
  - 7.2

services:
  - mysql

addons:
  apt:
    packages:
      - parallel

env:
  global:
    - CODACY_PROJECT_TOKEN=727c375148344e04973a6ee108d3967e

cache:
  directories:
  - $HOME/.composer/cache

install:
  - >
    composer install --prefer-dist;
    composer build:package:link

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running unit tests";
    .build/bin/phpunit -c Build/UnitTests.xml
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    .build/bin/phpunit -c Build/FunctionalTests.xml --coverage-clover .build/coverage.xml;
    .build/bin/codacycoverage clover .build/coverage.xml
