services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  cache.gql:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['gql']

  TYPO3\CMS\GraphQL\:
    resource: '../Classes/*'

  TYPO3\CMS\GraphQL\Database\FilterArgumentProvider:
    tags:
      -
        name: event.listener
        identifier: 'entity-query-filter'
        event: TYPO3\CMS\GraphQL\Event\BeforeFieldArgumentsInitializationEvent

  TYPO3\CMS\GraphQL\Database\OrderArgumentProvider:
    tags:
      -
        name: event.listener
        identifier: 'entity-query-order'
        event: TYPO3\CMS\GraphQL\Event\BeforeFieldArgumentsInitializationEvent

  TYPO3\CMS\GraphQL\Database\RestrictionsArgumentProvider:
    tags:
      -
        name: event.listener
        identifier: 'entity-query-restrictions'
        event: TYPO3\CMS\GraphQL\Event\BeforeFieldArgumentsInitializationEvent

  TYPO3\CMS\GraphQL\Database\FieldQueryHandler:
    tags:
      -
        name: event.listener
        identifier: 'entity-query-field'
        event: TYPO3\CMS\GraphQL\Event\BeforeValueResolvingEvent

  TYPO3\CMS\GraphQL\Database\FilterQueryHandler:
    tags:
      -
        name: event.listener
        identifier: 'entity-query-filter'
        event: TYPO3\CMS\GraphQL\Event\BeforeValueResolvingEvent

  TYPO3\CMS\GraphQL\Database\OrderQueryHandler:
    tags:
      -
        name: event.listener
        identifier: 'entity-query-order'
        event: TYPO3\CMS\GraphQL\Event\BeforeValueResolvingEvent

  TYPO3\CMS\GraphQL\Database\OrderValueHandler:
    tags:
      -
        name: event.listener
        identifier: 'entity-query-order'
        event: TYPO3\CMS\GraphQL\Event\AfterValueResolvingEvent

  TYPO3\CMS\GraphQL\Database\RestrictionsQueryHandler:
    tags:
      -
        name: event.listener
        identifier: 'entity-query-restrictions'
        event: TYPO3\CMS\GraphQL\Event\BeforeValueResolvingEvent